### ISSUE TITLE
cuckaroo_verify illegal instruction

### ISSUE THREAD

**Issue by muscleman** [CortexFoundation/CortexTheseus#1173]
~/CortexTheseus/solution/src/cpu/miner.cpp

`int32_t CuckooVerifyProof_cuckaroo(uint8_t *header, uint64_t nonce, result_t *result)
{
    uint64_t littleEndianNonce = htole64(nonce);
    char headerBuf[40];
    memcpy(headerBuf, header, 32);
    memcpy(headerBuf + 32, static_cast<uint64_t*>(&littleEndianNonce), sizeof(nonce));
    siphash_keys keys;
    setheader(headerBuf, 40, &keys);
    printf(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>header<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\n");
    int res = cuckaroo_verify(result, keys);
    return res;
}`

I'm running Ubuntu 20.04

cuckaroo_verify is throwing illegal instruction exceptions while attempting to verify blocks during synchronization.

i can comment out the above line returning true and my node will fully sync.

`INFO [02-05|23:56:10.365|ctxc/downloader/downloader.go:346]                                   Block synchronisation started 
INFO [02-05|23:56:15.387|ctxc/downloader/queue.go:391]                                        Downloader queue stats                   receiptTasks=0 blockTasks=154 itemSize=740.23B throttle=8192
SIGILL: illegal instruction
PC=0x1a1544e m=69 sigcode=2
instruction bytes: 0xc5 0xfa 0x6f 0x7 0x64 0x48 0x8b 0x4 0x25 0x28 0x0 0x0 0x0 0x48 0x89 0x44

goroutine 0 [idle]:
runtime: unknown pc 0x1a1544e
stack: frame={sp:0x7fc457efed90, fp:0x0} stack=[0x7fc4576ff270,0x7fc457efee70)
0x00007fc457efec90:  0x0000000000b2f62a <runtime.mapaccess1+0x000000000000006a>  0x0000000100004adb 
0x00007fc457efeca0:  0x0000000000000000  0x00007fc457efee58 
0x00007fc457efecb0:  0x0000000000b70da7 <runtime.newstack+0x00000000000004a7>  0x000000c01e9a8518 
0x00007fc457efecc0:  0x0000000200000008  0x000000500000000a 
0x00007fc457efecd0:  0x0000000d00000017  0x0000000000b52cd6 <runtime.futexwakeup+0x0000000000000036> 
0x00007fc457efece0:  0x000000c001338150  0x000000c01e1dcb88 
0x00007fc457efecf0:  0x0000000000000000  0x000000c01f380000 
0x00007fc457efed00:  0x0000000000000800  0x0000000000001000 
0x00007fc457efed10:  0x00007fc457efed30  0x00007ffcc2bc8918 
0x00007fc457efed20:  0x00007fc457efed58  0x000000c01e1dcba0 
0x00007fc457efed30:  0x00007fc457efed68  0x0000000000b8cf53 <runtime.nanotime1+0x0000000000000073> 
0x00007fc457efed40:  0x0000000000001000  0x0000000024af61d0 
0x00007fc457efed50:  0x00007fc457efed98  0x0000000000000000 
0x00007fc457efed60:  0x0000000000000000  0x00007fc457efedb0 
0x00007fc457efed70:  0x000000c01f3821a0  0x00116c788ca35fd0 
0x00007fc457efed80:  0x000000c01e9a84e0  0x00007fc457efeda0 
0x00007fc457efed90: <0x0000000000b49459 <runtime.newAllocBits+0x0000000000000019>  0x00007fc457efedb8 
0x00007fc457efeda0:  0x00007fc457efee10  0x0000000000b47c36 <runtime.(*mheap).allocSpan+0x0000000000000536> 
0x00007fc457efedb0:  0x000000c01e1dcb98  0x0000000000b237f6 <runtime.interhash+0x0000000000000056> 
0x00007fc457efedc0:  0x000000c01e9a84e0  0x0000000000000000 
0x00007fc457efedd0:  0x00007fc577d49118  0x0000000000000000 
0x00007fc457efede0:  0x000000c01fd16000  0x000000c017916798 
0x00007fc457efedf0:  0x000000c017917000  0x00000000019b4643 
0x00007fc457efee00:  0x000000c0179167d0  0x000000c017916798 
0x00007fc457efee10:  0x000000c01faf66c0  0x0000000000b8b270 <runtime.asmcgocall+0x0000000000000070> 
0x00007fc457efee20:  0x0000000002d84fa0  0x0000000000000001 
0x00007fc457efee30:  0x000000c01f934100  0x4100000400000002 
0x00007fc457efee40:  0x000000c01f3821a0  0x0000000000000898 
0x00007fc457efee50:  0x000000c01e9a84e0  0x000000c017916840 
0x00007fc457efee60:  0x0000000000b893c9 <runtime.systemstack+0x0000000000000049>  0x00007fc557ffea4e 
runtime: unknown pc 0x1a1544e
stack: frame={sp:0x7fc457efed90, fp:0x0} stack=[0x7fc4576ff270,0x7fc457efee70)
0x00007fc457efec90:  0x0000000000b2f62a <runtime.mapaccess1+0x000000000000006a>  0x0000000100004adb 
0x00007fc457efeca0:  0x0000000000000000  0x00007fc457efee58 
0x00007fc457efecb0:  0x0000000000b70da7 <runtime.newstack+0x00000000000004a7>  0x000000c01e9a8518 
0x00007fc457efecc0:  0x0000000200000008  0x000000500000000a 
0x00007fc457efecd0:  0x0000000d00000017  0x0000000000b52cd6 <runtime.futexwakeup+0x0000000000000036> 
0x00007fc457efece0:  0x000000c001338150  0x000000c01e1dcb88 
0x00007fc457efecf0:  0x0000000000000000  0x000000c01f380000 
0x00007fc457efed00:  0x0000000000000800  0x0000000000001000 
0x00007fc457efed10:  0x00007fc457efed30  0x00007ffcc2bc8918 
0x00007fc457efed20:  0x00007fc457efed58  0x000000c01e1dcba0 
0x00007fc457efed30:  0x00007fc457efed68  0x0000000000b8cf53 <runtime.nanotime1+0x0000000000000073> 
0x00007fc457efed40:  0x0000000000001000  0x0000000024af61d0 
0x00007fc457efed50:  0x00007fc457efed98  0x0000000000000000 
0x00007fc457efed60:  0x0000000000000000  0x00007fc457efedb0 
0x00007fc457efed70:  0x000000c01f3821a0  0x00116c788ca35fd0 
0x00007fc457efed80:  0x000000c01e9a84e0  0x00007fc457efeda0 
0x00007fc457efed90: <0x0000000000b49459 <runtime.newAllocBits+0x0000000000000019>  0x00007fc457efedb8 
0x00007fc457efeda0:  0x00007fc457efee10  0x0000000000b47c36 <runtime.(*mheap).allocSpan+0x0000000000000536> 
0x00007fc457efedb0:  0x000000c01e1dcb98  0x0000000000b237f6 <runtime.interhash+0x0000000000000056> 
0x00007fc457efedc0:  0x000000c01e9a84e0  0x0000000000000000 
0x00007fc457efedd0:  0x00007fc577d49118  0x0000000000000000 
0x00007fc457efede0:  0x000000c01fd16000  0x000000c017916798 
0x00007fc457efedf0:  0x000000c017917000  0x00000000019b4643 
0x00007fc457efee00:  0x000000c0179167d0  0x000000c017916798 
0x00007fc457efee10:  0x000000c01faf66c0  0x0000000000b8b270 <runtime.asmcgocall+0x0000000000000070> 
0x00007fc457efee20:  0x0000000002d84fa0  0x0000000000000001 
0x00007fc457efee30:  0x000000c01f934100  0x4100000400000002 
0x00007fc457efee40:  0x000000c01f3821a0  0x0000000000000898 
0x00007fc457efee50:  0x000000c01e9a84e0  0x000000c017916840 
0x00007fc457efee60:  0x0000000000b893c9 <runtime.systemstack+0x0000000000000049>  0x00007fc557ffea4e 
`
here is my system information

`gru@minion CortexTheseus-Fixed (master) $ uname -r
5.4.0-91-generic
gru@minion CortexTheseus-Fixed (master) $ lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   44 bits physical, 48 bits virtual
CPU(s):                          80
On-line CPU(s) list:             0-79
Thread(s) per core:              2
Core(s) per socket:              10
Socket(s):                       4
NUMA node(s):                    4
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           47
Model name:                      Intel(R) Xeon(R) CPU E7- 8870  @ 2.40GHz
Stepping:                        2
Frequency boost:                 enabled
CPU MHz:                         2488.603
CPU max MHz:                     2395.0000
CPU min MHz:                     1064.0000
BogoMIPS:                        4788.13
Virtualization:                  VT-x
L1d cache:                       1.3 MiB
L1i cache:                       1.3 MiB
L2 cache:                        10 MiB
L3 cache:                        120 MiB
NUMA node0 CPU(s):               0,4,8,12,16,20,24,28,32,36,40,44,48,52,56,60,64,68,72,76
NUMA node1 CPU(s):               1,5,9,13,17,21,25,29,33,37,41,45,49,53,57,61,65,69,73,77
NUMA node2 CPU(s):               2,6,10,14,18,22,26,30,34,38,42,46,50,54,58,62,66,70,74,78
NUMA node3 CPU(s):               3,7,11,15,19,23,27,31,35,39,43,47,51,55,59,63,67,71,75,79
Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl x
                                 topology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt aes lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow
                                  vnmi flexpriority ept vpid dtherm ida arat flush_l1d
`

**Comment by muscleman** [comment]
this could be as easy as a different g++ or gcc compiler switch right

**Comment by muscleman** [comment]
my cpu doesn't have avx2 for SIPHASH=8
