### ISSUE TITLE
SIGILL: illegal instruction

### ISSUE THREAD

**Issue by wpbloger** [CortexFoundation/CortexTheseus#923]
Hello.
I wanted to run a full node, but an error occurs when trying to sync.
Here's the output: 
```
INFO [03-29|19:08:11.623|cortex/main.go:302] Bumping default cache on mainnet         provided=1024 updated=4096
[0mINFO [03-29|19:08:11.623|cortex/main.go:324] Sanitizing Go's GC trigger               percent=25 cache=4096
[0mINFO [03-29|19:08:11.626|cmd/utils/flags.go:1129] Maximum peer count                       Cortex=50 total=50
[0mINFO [03-29|19:08:11.626|cmd/utils/flags.go:1488] Set global gas cap                       cap=25000000
[0mINFO [03-29|19:08:11.627|node/node.go:194]        Starting peer-to-peer node               instance=Cortex/v1.10.22-stable-c6dcda20/linux-amd64/go1.16
[0mINFO [03-29|19:08:11.627|vendor/github.com/CortexFoundation/torrentfs/chaindb.go:621] Start from block number (default:0)      num=0
[0mINFO [03-29|19:08:11.645|vendor/github.com/CortexFoundation/torrentfs/chaindb.go:524] File init finished                       files=0 total=0
[0mINFO [03-29|19:08:11.661|vendor/github.com/CortexFoundation/torrentfs/chaindb.go:476] Fs blocks initializing ... ...           blocks=0 txs=0
[0mINFO [03-29|19:08:11.678|vendor/github.com/CortexFoundation/torrentfs/chaindb.go:181] Storage merkletree initialization        root=0x0d6ab1af1844adbbab182db393543ba4c29c26bf42affc3756ed87c6c00c6b24 number=0 checkpoint=0 version=2 len=0
[0mINFO [03-29|19:08:11.678|vendor/github.com/CortexFoundation/torrentfs/chaindb.go:122] Storage ID generated                     id=14576225956359564527
[0mINFO [03-29|19:08:11.678|vendor/github.com/CortexFoundation/torrentfs/sync.go:92]     File storage initialized 
[0mINFO [03-29|19:08:11.679|vendor/github.com/CortexFoundation/torrentfs/handler.go:437] Listening local                          port=40401
[0mINFO [03-29|19:08:11.802|vendor/github.com/CortexFoundation/torrentfs/handler.go:497] Hot cache created                        size=17
[0mINFO [03-29|19:08:11.802|vendor/github.com/CortexFoundation/torrentfs/handler.go:211] Boot trackers                            t="[[udp://tracker.cortexlabs.ai:5008 udp://tracker.openbittorrent.com:80 udp://tracker.opentrackr.org:1337/announce]]"
[0mINFO [03-29|19:08:11.802|vendor/github.com/CortexFoundation/torrentfs/sync.go:99]     Fs manager initialized 
[0mINFO [03-29|19:08:11.803|vendor/github.com/CortexFoundation/torrentfs/chaindb.go:810] Torrent initializing ... ...             torrents=0
[0mINFO [03-29|19:08:11.805|vendor/github.com/CortexFoundation/torrentfs/torrent.go:180] Imported new nas segment                 ih=aea5584d0cd3865e90c80eace3bfcb062473d966 size=3.12KiB files=1 pieces=1 seg=1 cited=0 peers=25 status=7 elapsed="655.042µs"
[0mINFO [03-29|19:08:11.809|vendor/github.com/CortexFoundation/torrentfs/torrent.go:180] Imported new nas segment                 ih=3145ad19228c1cd2d051314e72f26c1ce77b7f02 size=398.21KiB files=2 pieces=25 seg=1 cited=0 peers=25 status=7 elapsed="265.746µs"
[0mINFO [03-29|19:08:11.809|vendor/github.com/CortexFoundation/torrentfs/torrent.go:180] Imported new nas segment                 ih=ae5a301ddfe1d4be9848adf8dde9f78d7ebba919 size=3.12KiB   files=1 pieces=1  seg=1 cited=0 peers=25 status=7 elapsed="105.46µs"
[0mINFO [03-29|19:08:11.811|vendor/github.com/CortexFoundation/torrentfs/torrent.go:180] Imported new nas segment                 ih=9f222b4afa685d74d82e88972922cc9108a81791 size=147.12KiB files=1 pieces=10 seg=1 cited=0 peers=25 status=7 elapsed="330.42µs"
[0mINFO [03-29|19:08:11.811|vendor/github.com/CortexFoundation/torrentfs/torrent.go:256] Donwloaded pieces                        ih=04615009127a4829d32d22dddb45664a2aee8067 s=0 e=10 p=10 total=10
[0mWARN [03-29|19:08:11.819|vendor/github.com/CortexFoundation/torrentfs/sync.go:135]    Data reloading                           mode=normal
[0mINFO [03-29|19:08:11.820|vendor/github.com/CortexFoundation/torrentfs/sync.go:210]    Storage current state                    total=0  dis=0 seed=0 pause=0 pending=0 capcity=0.00B blocks=0 txs=0
[0mINFO [03-29|19:08:11.820|ctxc/backend.go:117]                                         Allocated trie memory caches             clean=1023.00MiB dirty=1024.00MiB snapshot=0.00B NoPruning=false
[0mINFO [03-29|19:08:11.820|ctxcdb/leveldb/leveldb.go:95]                                Allocated cache and file handles         database=/home/user/.cortex/cortex/chaindata cache=2.00GiB handles=512
[0mINFO [03-29|19:08:11.851|vendor/github.com/CortexFoundation/torrentfs/torrent.go:180] Imported new nas segment                 ih=9dbde0099a270c23d5dec0acb0ac537b0fb35c27 size=4.15MiB   files=2 pieces=266 seg=1 cited=0 peers=25 status=7 elapsed="333.632µs"
[0mINFO [03-29|19:08:11.856|vendor/github.com/CortexFoundation/torrentfs/torrent.go:180] Imported new nas segment                 ih=3df6926c165db01330574fba8c23aa7b03311356 size=436.43KiB files=2 pieces=28  seg=1 cited=0 peers=25 status=7 elapsed="239.974µs"
[0mINFO [03-29|19:08:11.858|vendor/github.com/CortexFoundation/torrentfs/torrent.go:180] Imported new nas segment                 ih=ad3d77101866c0c7520aa41a5c41eee92500f809 size=147.12KiB files=1 pieces=10  seg=1 cited=0 peers=25 status=7 elapsed="241.581µs"
[0mINFO [03-29|19:08:11.875|vendor/github.com/CortexFoundation/torrentfs/torrent.go:180] Imported new nas segment                 ih=5a49fed84aaf368cbf472cc06e42f93a93d92db5 size=1.57MiB   files=2 pieces=101 seg=1 cited=0 peers=25 status=7 elapsed="257.017µs"
[0mINFO [03-29|19:08:11.878|vendor/github.com/CortexFoundation/torrentfs/torrent.go:180] Imported new nas segment                 ih=ec6b1f5b5073c07dd35a53a3a13220c1a21e426d size=147.12KiB files=1 pieces=10  seg=1 cited=0 peers=25 status=7 elapsed="254.362µs"
[0mINFO [03-29|19:08:11.878|vendor/github.com/CortexFoundation/torrentfs/torrent.go:180] Imported new nas segment                 ih=b3d2f3d4f395924ca4cf5bd1843d49de043c959c size=3.12KiB   files=1 pieces=1   seg=1 cited=0 peers=25 status=7 elapsed="322.946µs"
[0mINFO [03-29|19:08:11.879|vendor/github.com/CortexFoundation/torrentfs/torrent.go:256] Donwloaded pieces                        ih=67b315aac2fbdbaf97ac8d40df0b9c435b65c4aa s=0 e=1  p=1  total=1
[0mINFO [03-29|19:08:11.882|vendor/github.com/CortexFoundation/torrentfs/torrent.go:180] Imported new nas segment                 ih=de58609743e5cd0cb18798d91a196f418ac25016 size=147.12KiB files=1 pieces=10  seg=1 cited=0 peers=25 status=7 elapsed="235.924µs"
[0mINFO [03-29|19:08:12.079|vendor/github.com/CortexFoundation/torrentfs/torrent.go:180] Imported new nas segment                 ih=c599d0fa8d816cf83c5018232453c6ae57db4ab3 size=24.75MiB  files=2 pieces=792 seg=1 cited=0 peers=25 status=7 elapsed=10.859ms
[0mINFO [03-29|19:08:12.080|vendor/github.com/CortexFoundation/torrentfs/torrent.go:256] Donwloaded pieces                        ih=3101ac2c157ace6e4be72575758f7ba62b53e219 s=0 e=10 p=10 total=10
[0mINFO [03-29|19:08:12.082|vendor/github.com/CortexFoundation/torrentfs/torrent.go:180] Imported new nas segment                 ih=1fb97d6da1761ddc051446307bd915506359a17a size=147.12KiB files=1 pieces=10  seg=1 cited=0 peers=25 status=7 elapsed="214.273µs"
[0mINFO [03-29|19:08:12.083|vendor/github.com/CortexFoundation/torrentfs/torrent.go:180] Imported new nas segment                 ih=a83dc64f96494b6b6c4f5291196d0ddd2f1a0769 size=147.12KiB files=1 pieces=10  seg=1 cited=0 peers=25 status=7 elapsed="186.058µs"
[0mINFO [03-29|19:08:12.085|vendor/github.com/CortexFoundation/torrentfs/torrent.go:180] Imported new nas segment                 ih=3f1f6c007e8da3e16f7c3378a20a746e70f1c2b0 size=147.12KiB files=1 pieces=10  seg=1 cited=0 peers=25 status=7 elapsed="183.962µs"
[0mINFO [03-29|19:08:12.095|vendor/github.com/CortexFoundation/torrentfs/torrent.go:256] Donwloaded pieces                        ih=d31d1b0f588069aa6f36de5a7025a8d73a9a49f6 s=0 e=973 p=973 total=973
[0mINFO [03-29|19:08:12.098|vendor/github.com/CortexFoundation/torrentfs/torrent.go:180] Imported new nas segment                 ih=b08e2c6103157ab99040cdc9ddfee05e93763f6c size=147.12KiB files=1 pieces=10  seg=1 cited=0 peers=25 status=7 elapsed="430.083µs"
[0mINFO [03-29|19:08:12.102|vendor/github.com/CortexFoundation/torrentfs/torrent.go:180] Imported new nas segment                 ih=1f1706fa53ce0723ba1c577418b222acbfa5a200 size=439.45KiB files=2 pieces=28  seg=1 cited=0 peers=25 status=7 elapsed="802.407µs"
[0mINFO [03-29|19:08:12.103|vendor/github.com/CortexFoundation/torrentfs/torrent.go:180] Imported new nas segment                 ih=b2f5b0036877be22c6101bdfa5f2c7927fc35ef8 size=33.46KiB  files=2 pieces=3   seg=1 cited=0 peers=25 status=7 elapsed="538.617µs"
[0mINFO [03-29|19:08:12.103|vendor/github.com/CortexFoundation/torrentfs/torrent.go:180] Imported new nas segment                 ih=6b75cc1354495ec763a6b295ee407ea864a0c292 size=33.78KiB  files=2 pieces=3   seg=1 cited=0 peers=25 status=7 elapsed="315.473µs"
[0mINFO [03-29|19:08:12.112|vendor/github.com/CortexFoundation/torrentfs/torrent.go:256] Donwloaded pieces                        ih=6dfc52c480a779dd3e2c9dce9772a5131ee1f4d7 s=0 e=789 p=789 total=789
[0mINFO [03-29|19:08:12.224|core/rawdb/freezer.go:133]                                   Opened ancient database                  database=/home/user/.cortex/cortex/chaindata/ancient
[0mINFO [03-29|19:08:12.225|ctxc/backend.go:128]                                         Initialised chain configuration          config="{ChainID: 21 Homestead: 0 DAO: 0 DAOSupport: false TangerineWhistle(EIP150): 0 SpuriousDragon(EIP155): 0 SpuriousDragon(EIP158): 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 3230000 Engine: cuckoo}"
[0mWARN [03-29|19:08:12.226|consensus/cuckoo/cuckoo.go:224]                              Memory status                            total=24036 allowance=8012 cuda=false device= threads=0 algo=cuckaroo
[0mINFO [03-29|19:08:12.226|ctxc/backend.go:151]                                         Initialising Cortex protocol             versions="[65 64]" network=21 dbversion=8
[0mINFO [03-29|19:08:12.229|vendor/github.com/CortexFoundation/inference/synapse/synapse.go:120] Initialising Synapse Engine              Cache Disabled=false
[0mINFO [03-29|19:08:12.231|core/blockchain.go:474]                                              Loaded most recent local header          number=0 hash="21d6ce…7762c1" td=512 age=51y11mo3w
[0mINFO [03-29|19:08:12.231|core/blockchain.go:475]                                              Loaded most recent local full block      number=0 hash="21d6ce…7762c1" td=512 age=51y11mo3w
[0mINFO [03-29|19:08:12.231|core/blockchain.go:476]                                              Loaded most recent local fast block      number=0 hash="21d6ce…7762c1" td=512 age=51y11mo3w
[0mINFO [03-29|19:08:12.232|core/tx_journal.go:114]                                              Loaded local transaction journal         transactions=0 dropped=0
[0mINFO [03-29|19:08:12.232|core/tx_journal.go:166]                                              Regenerated local transaction journal    transactions=0 accounts=0
[0mINFO [03-29|19:08:12.232|ctxc/handler.go:154]                                                 Check point                              section=104 number=3440639 hash="f66995…ccb90a" genesis="21d6ce…7762c1" ok=true
[0mWARN [03-29|19:08:12.233|ctxc/backend.go:237]                                                 Old unclean shutdowns found              count=1
[0mWARN [03-29|19:08:12.233|ctxc/backend.go:241]                                                 Unclean shutdown detected                booted=2021-03-29T14:44:54+0400 age=4h23m18s
[0mWARN [03-29|19:08:12.233|ctxc/backend.go:241]                                                 Unclean shutdown detected                booted=2021-03-29T14:47:58+0400 age=4h20m14s
[0mWARN [03-29|19:08:12.233|ctxc/backend.go:241]                                                 Unclean shutdown detected                booted=2021-03-29T14:49:11+0400 age=4h19m1s
[0mWARN [03-29|19:08:12.233|ctxc/backend.go:241]                                                 Unclean shutdown detected                booted=2021-03-29T14:53:32+0400 age=4h14m40s
[0mWARN [03-29|19:08:12.233|ctxc/backend.go:241]                                                 Unclean shutdown detected                booted=2021-03-29T14:53:46+0400 age=4h14m26s
[0mWARN [03-29|19:08:12.233|ctxc/backend.go:241]                                                 Unclean shutdown detected                booted=2021-03-29T14:54:09+0400 age=4h14m3s
[0mWARN [03-29|19:08:12.233|ctxc/backend.go:241]                                                 Unclean shutdown detected                booted=2021-03-29T15:01:05+0400 age=4h7m7s
[0mWARN [03-29|19:08:12.233|ctxc/backend.go:241]                                                 Unclean shutdown detected                booted=2021-03-29T17:38:41+0400 age=1h29m31s
[0mWARN [03-29|19:08:12.233|ctxc/backend.go:241]                                                 Unclean shutdown detected                booted=2021-03-29T18:22:17+0400 age=45m55s
[0mWARN [03-29|19:08:12.233|ctxc/backend.go:241]                                                 Unclean shutdown detected                booted=2021-03-29T18:53:08+0400 age=15m4s
[0mWARN [03-29|19:08:12.233|ctxc/backend.go:241]                                                 Unclean shutdown detected                booted=2021-03-29T19:07:15+0400 age=57s
[0mINFO [03-29|19:08:12.410|vendor/github.com/CortexFoundation/torrentfs/fs.go:237]              Started nas v.1.0                        config="&{protocol:{Name:nas Version:2 Length:128 Run:0x1331b80 NodeInfo:0x132ee80 PeerInfo:0x132f5c0 DialCandidates:<nil> Attributes:[]} config:0xc0002e85e8 monitor:0xc00527e0b0 peerMu:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:0 readerWait:0} peers:map[] nasCache:0xc000113f20 queryCache:0xc000113f80 nasCounter:0}" mode=normal
[0mINFO [03-29|19:08:12.410|p2p/server.go:695]                                                   Started P2P networking                   self=enode://9b1277912b0e57d38818f13e2feec2629a6ef0d8875368a8f2ab2edf4b76223e5a39b372cd9d9efaf726148180b8f016e4e6040b6d82808d15eb13534e853f08@127.0.0.1:40404
[0mINFO [03-29|19:08:12.413|node/node.go:351]                                                    IPC endpoint opened                      url=/home/user/.cortex/cortex.ipc
[0mINFO [03-29|19:08:12.528|p2p/nat/nat.go:110]                                                  Mapped network port                      proto=tcp extport=40404 intport=40404 interface=NAT-PMP(192.168.1.1)
[0mINFO [03-29|19:08:12.528|p2p/nat/nat.go:110]                                                  Mapped network port                      proto=udp extport=40404 intport=40404 interface=NAT-PMP(192.168.1.1)
[0mINFO [03-29|19:08:13.771|ctxc/downloader/downloader.go:361]                                   Block synchronisation started 
[0mINFO [03-29|19:08:14.412|vendor/github.com/CortexFoundation/torrentfs/sync.go:249]            Internal ipc connection established      ipc=/home/user/.cortex/cortex.ipc rpc=http://127.0.0.1:8545 local=true
[0mINFO [03-29|19:08:14.412|vendor/github.com/CortexFoundation/torrentfs/sync.go:143]            Loading storage data ... ...             latest=0 checkpoint=0 root="0d6ab1…0c6b24" version=2 current=0
[0mWARN [03-29|19:08:14.413|vendor/github.com/CortexFoundation/torrentfs/sync.go:164]            Fs storage is reloading ...              name=mainnet number=395964  version="000000…000000" checkpoint="e78706…7e5dcc" blocks=0 files=0 txs=0 lastNumber=0 last in db=0
[0mINFO [03-29|19:08:15.117|vendor/github.com/CortexFoundation/torrentfs/torrent.go:180]         Imported new nas segment                 ih=67b315aac2fbdbaf97ac8d40df0b9c435b65c4aa size=3.12KiB   files=1 pieces=1   seg=1 cited=0 peers=25 status=7 elapsed=3.237s
[0mINFO [03-29|19:08:16.831|ctxc/downloader/queue.go:391]                                        Downloader queue stats                   receiptTasks=0 blockTasks=167 itemSize=755.58B throttle=8192
[0mSIGILL: illegal instruction
PC=0x183620e m=8 sigcode=2
instruction bytes: 0xc4 0xe3 0x65 0x38 0x4a 0x10 0x1 0xc5 0xfa 0x6f 0x62 0x20 0xc5 0xfa 0x6f 0x6a

goroutine 0 [idle]:
runtime: unknown pc 0x183620e
stack: frame={sp:0x7f03067fb9f8, fp:0x0} stack=[0x7f0305ffc288,0x7f03067fbe88)
00007f03067fb8f8:  0000000000000000  0000000000000000 
00007f03067fb908:  0000000000000003  0000000000a7baa0 <sync.(*Pool).Put+0> 
00007f03067fb918:  0000000000a61201 <runtime.goexit+1>  0000000000022b89 
00007f03067fb928:  0000000000000000  0000000000000000 
00007f03067fb938:  00000000009f00b3 <runtime.interhash+371>  0000000000000bc2 
00007f03067fb948:  0000000000000000  0000000000000000 
00007f03067fb958:  0000000000000000  0000000000000000 
00007f03067fb968:  0000000000000000  0000000000000000 
00007f03067fb978:  0000000000bcdb85 <github.com/CortexFoundation/CortexTheseus/rlp.(*encbuf).encode+229>  0000006000071046 
00007f03067fb988:  0000000001846328  00007f03067fbac0 
00007f03067fb998:  00000000013d389c <github.com/CortexFoundation/CortexTheseus/consensus/cuckoo.(*Cuckoo).verifyHeaderWorker+508>  00007f03067fba80 
00007f03067fb9a8:  00007f03067fba60  00007f03067fba88 
00007f03067fb9b8:  00007f03067fba68  00007f03067fba48 
00007f03067fb9c8:  00007f03067fba70  00007f03067fba50 
00007f03067fb9d8:  00007f03067fba78  00007f03067fba58 
00007f03067fb9e8:  00007f03067fbab8  00007f03067fba90 
00007f03067fb9f8: <0000000000000000  0000000000000000 
00007f03067fba08:  00000000018364fd  00007f03067fbdb0 
00007f03067fba18:  00007f03067fbb70  00007f03067fbac0 
00007f03067fba28:  00007f03067fbc40  ffffffffffffffff 
00007f03067fba38:  00000000018464e3  206a1d04295b2a82 
00007f03067fba48:  1518b68f4e75adda  1df77755ef278159 
00007f03067fba58:  9979641a676c9171  a8effd354b5b0469 
00007f03067fba68:  90b171a21c8b8fa9  0264d42dd9e775d9 
00007f03067fba78:  48dcd3fa90c5cef3  3fe62a6a8c4c53af 
00007f03067fba88:  5251cc370a3b5f07  99242066c8d37994 
00007f03067fba98:  a5f83cc8b51e72e9  fdb3bf939cd97fbe 
00007f03067fbaa8:  55222fa89e9ce4a8  deca2507217c1406 
00007f03067fbab8:  a7425b968ff89c4c  0a41164943553f6f 
00007f03067fbac8:  b647e4542b90b29c  245c8575d91481be 
00007f03067fbad8:  d40c29eb660ba2ae  1e89390404c6abf1 
00007f03067fbae8:  0000000000000000  0000000000000000 
runtime: unknown pc 0x183620e
stack: frame={sp:0x7f03067fb9f8, fp:0x0} stack=[0x7f0305ffc288,0x7f03067fbe88)
00007f03067fb8f8:  0000000000000000  0000000000000000 
00007f03067fb908:  0000000000000003  0000000000a7baa0 <sync.(*Pool).Put+0> 
00007f03067fb918:  0000000000a61201 <runtime.goexit+1>  0000000000022b89 
00007f03067fb928:  0000000000000000  0000000000000000 
00007f03067fb938:  00000000009f00b3 <runtime.interhash+371>  0000000000000bc2 
00007f03067fb948:  0000000000000000  0000000000000000 
00007f03067fb958:  0000000000000000  0000000000000000 
00007f03067fb968:  0000000000000000  0000000000000000 
00007f03067fb978:  0000000000bcdb85 <github.com/CortexFoundation/CortexTheseus/rlp.(*encbuf).encode+229>  0000006000071046 
00007f03067fb988:  0000000001846328  00007f03067fbac0 
00007f03067fb998:  00000000013d389c <github.com/CortexFoundation/CortexTheseus/consensus/cuckoo.(*Cuckoo).verifyHeaderWorker+508>  00007f03067fba80 
00007f03067fb9a8:  00007f03067fba60  00007f03067fba88 
00007f03067fb9b8:  00007f03067fba68  00007f03067fba48 
00007f03067fb9c8:  00007f03067fba70  00007f03067fba50 
00007f03067fb9d8:  00007f03067fba78  00007f03067fba58 
00007f03067fb9e8:  00007f03067fbab8  00007f03067fba90 
00007f03067fb9f8: <0000000000000000  0000000000000000 
00007f03067fba08:  00000000018364fd  00007f03067fbdb0 
00007f03067fba18:  00007f03067fbb70  00007f03067fbac0 
00007f03067fba28:  00007f03067fbc40  ffffffffffffffff 
00007f03067fba38:  00000000018464e3  206a1d04295b2a82 
00007f03067fba48:  1518b68f4e75adda  1df77755ef278159 
00007f03067fba58:  9979641a676c9171  a8effd354b5b0469 
00007f03067fba68:  90b171a21c8b8fa9  0264d42dd9e775d9 
00007f03067fba78:  48dcd3fa90c5cef3  3fe62a6a8c4c53af 
00007f03067fba88:  5251cc370a3b5f07  99242066c8d37994 
00007f03067fba98:  a5f83cc8b51e72e9  fdb3bf939cd97fbe 
00007f03067fbaa8:  55222fa89e9ce4a8  deca2507217c1406 
00007f03067fbab8:  a7425b968ff89c4c  0a41164943553f6f 
00007f03067fbac8:  b647e4542b90b29c  245c8575d91481be 
00007f03067fbad8:  d40c29eb660ba2ae  1e89390404c6abf1 
00007f03067fbae8:  0000000000000000  0000000000000000 

goroutine 6018 [syscall]:
runtime.cgocall(0x171cfe0, 0xc01732f7b8, 0x9)
	/usr/local/go/src/runtime/cgocall.go:154 +0x5b fp=0xc01732f788 sp=0xc01732f750 pc=0x9f145b
github.com/CortexFoundation/CortexTheseus/consensus/cuckoo/plugins._Cfunc_CuckooVerifyProof_cuckaroo(0xc017a4ffa0, 0x1e89390404c6abf1, 0xc0162508f0, 0xc000000000)
	_cgo_gotypes.go:67 +0x48 fp=0xc01732f7b8 sp=0xc01732f788 pc=0x13d0848
github.com/CortexFoundation/CortexTheseus/consensus/cuckoo/plugins.CuckooVerify_cuckaroo(0xc017a4ffa0, 0x1e89390404c6abf1, 0xcb21b3001ca78a, 0x584e530010e6374, 0x7a1724c078763c0, 0xb67242809679f35, 0xc8f76a90befd416, 0xda5ed000d6ea9a5, 0xf7e070f0ec17280, 0x113f92221044b959, ...)
	
	.....................
	

goroutine 5858 [select]:
net.(*netFD).connect.func2(0x1da2498, 0xc0177ccc00, 0xc0177ec080, 0xc015afd8c0, 0xc015afd860)
	/usr/local/go/src/net/fd_unix.go:118 +0x8a
created by net.(*netFD).connect
	/usr/local/go/src/net/fd_unix.go:117 +0x253

rax    0x7d6d619b44354a0c
rbx    0xa26030fc974d4716
rcx    0x7d6d619b44354a0c
rdx    0x7f03067fbb70
rdi    0x40
rsi    0xa
rbp    0x7f03067fba00
rsp    0x7f03067fb9f8
r8     0x1ca780
r9     0x3587c7ffc789dece
r10    0xd7c5122938f5a7d
r11    0xadfd4d32f92e87d1
r12    0xc0162508f0
r13    0x1
r14    0x7f03067fba20
r15    0x0
rip    0x183620e
rflags 0x10206
cs     0x33
fs     0x0
gs     0x0
```
gcc --version = 8.3.0
g++ --version = 8.3.0
go version = go1.16 linux/amd64

**Comment by ucwong** [comment]
binary or local build ?

**Comment by wpbloger** [comment]
@ucwong from the source code as described in the readme.
I tried make it on different processors, the result is the same.

**Comment by ucwong** [comment]
What about more details about the OS ?

**Comment by wpbloger** [comment]
@ucwong Debian 4.19.0-16-amd64, x86_64

**Comment by ucwong** [comment]
It seems not all instructions used by cuckoo matches with Debian, Make a try with ubuntu or centos

**Comment by effofxprime** [comment]
A Question for the OP.
Did you resolve this on your own?  I am having the same issue it appears.  However, I'm already on Ubuntu, 20.04.  Neither 1.16 or 1.16.3 of Go have worked for me.
If you got your node up, what did you do to resolve it?
